image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: on

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true"